-- ============================================================
-- DEPRECATED — do not use.
--
-- This file used to carry incremental "create the missing tables" statements that
-- drifted from db/schema.sql (two sources of truth), which caused two production
-- incidents in June 2026. It has been retired during the Aiven → Neon migration.
--
-- The single source of truth is now `db/schema.sql`. It is fully idempotent
-- (every statement is IF NOT EXISTS), so to provision or repair a database just run:
--
--   psql "$DATABASE_URL" -f db/schema.sql
--
-- Kept only as a tombstone so old links/bookmarks don't 404. Add nothing here.
-- ============================================================
